service: espnff-stats

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-finch

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  client:
    bucketName: espn-ff-stats-${self:provider.stage}
    distributionFolder: client/build/
    indexDocument: index.html
    errorDocument: index.html
  serverless-offline:
    port: 4000


package:
  individually: true

functions:
  graphql:
    handler: handlers/graphql.query
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
